baseURL = "https://atugo.me"
languageCode = "zh-cn"
title = "阿凸日记"
theme = "atu"

# 每页显示文章数量
paginate = 8

hasCJKLanguage = true
googleAnalytics = "UA-59524632-1"

OpenGraph = true

[Params]
enableComment = true

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:year/:month/:filename/"


[[menu.main]]
name = "归档"
url = "/posts"
weight = "100"
[[menu.main]]
name = "游戏"
url = "/text"
weight = "300"
[[menu.main]]
name = "关于"
url = "/about"
weight = "400"
[[menu.main]]
name = "建设"
url = "/construct"
pre = "<i class='fas fa-drafting-compass'></i>"
weight = "500"