baseURL = "https://atugo.me"
languageCode = "zh-cn"
title = "ATU"
theme = "atu"

# 每页显示文章数量
paginate = 5

hasCJKLanguage = true
googleAnalytics = "UA-59524632-1"

OpenGraph = true

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:year/:month/:filename/"
