name: hugo deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Connect To Tencent Server 
        uses: appleboy/ssh-action@master
        with: 
          host: atutang.com
          username: ubuntu
          key: ${{ secrets.ATU_SECRET }}
          port: 22
          script: |
            cd /var/www/hugo-theme-atu
            git pull

