name: hugo deployment

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          # submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true

      - name: Build
        run: hugo --minify

      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.ATU_SECRET }}

      - name: Scan public keys
        run: |
          ssh-keyscan ${{ secrets.ATU_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -av --delete public ubuntu@${{ secrets.ATU_HOST }}:/var/www/blog